- name: install postgresql and postgis
  hosts: dev
  become: true

  vars:
    postgres_version: 16
    postgres_user: fero
    postgres_password: fero@123
    postgres_db: ferodb

  tasks:
    - name: install required dependencies
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
          - apt-transport-https
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: create pgdg keyring directory
      file:
        path: /usr/share/postgresql-common/pgdg
        state: directory
        mode: "0755"
      check_mode: no

    - name: download PostgreSQL repository signing key
      get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
        mode: "0644"
        force: true
      check_mode: no

    - name: add PostgreSQL APT repository (official, signed-by)
      apt_repository:
        repo: "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"
        filename: pgdg
        state: present
      check_mode: no

    - name: update apt cache after adding PostgreSQL repo
      apt:
        update_cache: yes

    - name: install PostgreSQL and PostGIS
      apt:
        name:
          - postgresql-{{ postgres_version }}
          - postgresql-contrib-{{ postgres_version }}
          - postgresql-{{ postgres_version }}-postgis-3
          - postgresql-{{ postgres_version }}-postgis-3-scripts
        state: present

    - block:
        - name: ensure PostgreSQL service is running
          service:
            name: postgresql
            state: started
            enabled: true

        - name: create PostgreSQL user
          become_user: postgres
          community.postgresql.postgresql_user:
            name: "{{ postgres_user }}"
            password: "{{ postgres_password }}"
            role_attr_flags: SUPERUSER
            state: present

        - name: create database
          become_user: postgres
          community.postgresql.postgresql_db:
            name: "{{ postgres_db }}"
            owner: "{{ postgres_user }}"
            encoding: UTF8
            state: present

        - name: enable PostGIS extension
          become_user: postgres
          community.postgresql.postgresql_ext:
            name: postgis
            db: "{{ postgres_db }}"
            state: present
      when: not ansible_check_mode
